// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Ef.Models;

public partial class Todo
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public DateTime? Duedate { get; set; }

    public byte Status { get; set; }

    public string Tags { get; set; }

    public Guid Owner { get; set; }

    public byte? Priority { get; set; }
}